services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-airflow:2.9.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./utils:/opt/airflow/utils
      - ./config:/opt/airflow/config
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --firstname airflow --lastname airflow --role Admin --email admin@example.com --password admin &&
               airflow webserver"

  airflow-scheduler:
    build: .
    image: custom-airflow:2.9.0
    restart: always
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./utils:/opt/airflow/utils
      - ./config:/opt/airflow/config
    command: >
      bash -c "airflow db migrate && airflow scheduler"

volumes:
  postgres-db-volume: